/**
 * KitBannerLive — interactive React banner for the Weekly Kit view.
 *
 * Replaces the previous `<img src="…svg">` approach because external
 * `<image href>` references inside SVGs loaded via `<img>` tags don't
 * always render across browsers, leaving the kit looking like
 * "color + line + text" with no photo. This component uses a real
 * `<img>` tag for the photo and overlays the text/accents via React,
 * guaranteeing the photo always loads.
 *
 * Features:
 *   - Hero photo fills upper 65% of the card (visibly dominant)
 *   - Soft bottom gradient only behind the text block
 *   - Room-color left accent bar
 *   - Tier label + stat hero + 2-line headline
 *   - Hover: card lifts + photo subtle zoom + room-color halo breathes
 *   - "LIVE" badge with pulse animation in the upper-right
 *   - Source-freshness chip (e.g. "12h ago") when article carries it
 *
 * The SVG file generated by build-weekly-kit.mjs still exists at
 * /kit/<filenameBase>.svg for users who want to download a static
 * banner. The in-app preview uses this React component instead.
 */
import { useState } from 'react';
import type { RoomId } from '../../types';

export interface KitBannerLiveData {
  n: number;
  photoUrl?: string;
  room: RoomId;
  roomColor?: string;
  roomLabel?: string;
  postType?: string;
  typeLabel?: string;
  typeIcon?: string;
  typeAccent?: string;
  tier: string;
  stat?: string;
  headlineLine1?: string;
  headlineLine2?: string;
  hoursAgo?: number | null;
  title: string;
  framework: string;
  slot: { day: string; time: string };
}

const ROOM_COLOR_FALLBACK: Record<RoomId, string> = {
  growth: '#4ADE80',
  capital: '#F0C050',
  risk: '#EF5555',
  world: '#5B8DEE',
};

const ROOM_LABEL_FALLBACK: Record<RoomId, string> = {
  growth: 'GROWTH SIGNALS',
  capital: 'CAPITAL · CASH',
  risk: 'RISK · COMPLIANCE',
  world: 'WORLD PULSE',
};

export function KitBannerLive({ post }: { post: KitBannerLiveData }) {
  const [photoLoaded, setPhotoLoaded] = useState(false);
  const [photoError, setPhotoError] = useState(false);

  const roomColor = post.roomColor || ROOM_COLOR_FALLBACK[post.room];
  const roomLabel = post.roomLabel || ROOM_LABEL_FALLBACK[post.room];
  const typeAccent = post.typeAccent || '#A8926A';
  const typeLabel = post.typeLabel || 'OBSERVATION';
  const typeIcon = post.typeIcon || '';
  const hasStat = !!(post.stat && post.stat.trim());
  const hasPhoto = !!(post.photoUrl && !photoError);

  const freshness =
    post.hoursAgo == null ? null :
    post.hoursAgo < 1 ? 'JUST NOW' :
    post.hoursAgo < 24 ? `${post.hoursAgo}H AGO` :
    `${Math.floor(post.hoursAgo / 24)}D AGO`;

  return (
    <div
      className="
        group relative w-full aspect-square overflow-hidden rounded-card-lg
        bg-ink border border-ink-border
        transition-all duration-300 ease-out
        hover:shadow-[0_8px_40px_rgba(0,0,0,0.5)]
      "
      style={{ contain: 'content' }}
    >
      {/* PHOTO LAYER — actual <img> tag, guaranteed to load */}
      {hasPhoto && (
        <img
          src={post.photoUrl}
          alt=""
          loading="lazy"
          decoding="async"
          onLoad={() => setPhotoLoaded(true)}
          onError={() => setPhotoError(true)}
          className={`
            absolute inset-0 w-full h-full object-cover
            transition-all duration-500 ease-out
            group-hover:scale-[1.04]
            ${photoLoaded ? 'opacity-100' : 'opacity-0'}
          `}
          style={{
            filter: 'saturate(1.05) contrast(1.05)',
          }}
        />
      )}

      {/* Fallback gradient if photo fails or hasn't loaded yet */}
      {!hasPhoto && (
        <div
          className="absolute inset-0"
          style={{
            background: `radial-gradient(circle at 30% 30%, ${roomColor}22, #06060f 70%)`,
          }}
        />
      )}

      {/* Bottom gradient — only the lower 50% gets darkened for text */}
      <div
        className="absolute inset-x-0 bottom-0 h-[60%] pointer-events-none"
        style={{
          background: `linear-gradient(to bottom,
            transparent 0%,
            rgba(6,6,15,0.15) 25%,
            rgba(6,6,15,0.65) 65%,
            rgba(6,6,15,0.95) 100%)`,
        }}
      />

      {/* Top dark veil so the upper meta-row is readable */}
      <div
        className="absolute inset-x-0 top-0 h-[18%] pointer-events-none"
        style={{
          background: `linear-gradient(to bottom,
            rgba(6,6,15,0.55) 0%,
            rgba(6,6,15,0.2) 70%,
            transparent 100%)`,
        }}
      />

      {/* Room-color halo — breathes on hover */}
      <div
        className="absolute -inset-1 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-500"
        style={{
          background: `radial-gradient(circle at 80% 20%, ${roomColor}30, transparent 60%)`,
        }}
      />

      {/* Left accent bar */}
      <div
        className="absolute top-0 bottom-0 left-0 w-[6px]"
        style={{ background: roomColor }}
      />

      {/* TOP ZONE — meta row + LIVE indicator */}
      <div className="absolute inset-x-0 top-0 px-5 pt-4 flex items-start justify-between">
        <div className="flex flex-col gap-1">
          <span
            className="text-[10px] font-bold tracking-[0.18em]"
            style={{ color: '#A8926A' }}
          >
            MICS · CFOs PRIVATE
          </span>
          <span
            className="text-[9px] tracking-[0.15em]"
            style={{ color: 'rgba(234,230,222,0.75)' }}
          >
            {roomLabel}
          </span>
        </div>
        <div className="flex flex-col items-end gap-1.5">
          {/* LIVE pulse */}
          <div className="flex items-center gap-1">
            <span className="relative inline-flex h-1.5 w-1.5">
              <span
                className="absolute inline-flex h-full w-full animate-ping rounded-full opacity-75"
                style={{ background: roomColor }}
              />
              <span
                className="relative inline-flex h-1.5 w-1.5 rounded-full"
                style={{ background: roomColor }}
              />
            </span>
            <span
              className="text-[8px] font-bold tracking-[0.2em]"
              style={{ color: roomColor }}
            >
              LIVE
            </span>
          </div>
          {freshness && (
            <span
              className="text-[8px] font-bold tracking-[0.15em]"
              style={{ color: 'rgba(234,230,222,0.55)' }}
            >
              {freshness}
            </span>
          )}
        </div>
      </div>

      {/* TIER + POST-TYPE chip — middle-bottom */}
      <div className="absolute left-5 right-5 bottom-[40%] flex items-center gap-2 flex-wrap">
        <span
          className="text-[9px] font-bold tracking-[0.25em]"
          style={{ color: roomColor, textShadow: '0 1px 4px rgba(0,0,0,0.7)' }}
        >
          {post.tier}
        </span>
        <span
          className="text-[8px] font-bold tracking-wider px-1.5 py-0.5 rounded border"
          style={{
            color: typeAccent,
            background: `${typeAccent}22`,
            borderColor: `${typeAccent}55`,
          }}
        >
          {typeIcon} {typeLabel}
        </span>
      </div>

      {/* STAT — large serif hero (only when extracted) */}
      {hasStat && (
        <div
          className="absolute left-5 right-5 bottom-[26%] font-serif font-medium text-white"
          style={{
            fontFamily: '"Cormorant Garamond", Georgia, serif',
            fontSize: post.stat!.length > 8 ? '40px' : post.stat!.length > 5 ? '48px' : '56px',
            textShadow: '0 4px 24px rgba(0,0,0,0.6), 0 2px 8px rgba(0,0,0,0.4)',
            lineHeight: 1.1,
          }}
        >
          {post.stat}
        </div>
      )}

      {/* HEADLINE — 2-line serif */}
      <div
        className="absolute left-5 right-5 bottom-4 font-serif font-semibold text-[#EAE6DE]"
        style={{
          fontFamily: '"Cormorant Garamond", Georgia, serif',
          fontSize: hasStat ? '15px' : '20px',
          lineHeight: 1.25,
          textShadow: '0 2px 12px rgba(0,0,0,0.7), 0 1px 4px rgba(0,0,0,0.5)',
        }}
      >
        <div>{post.headlineLine1}</div>
        {post.headlineLine2 && <div>{post.headlineLine2}</div>}
      </div>

      {/* Slot tag — small bronze pill, bottom-right */}
      <div className="absolute right-3 bottom-3">
        <span
          className="text-[8px] font-bold tracking-[0.15em] px-1.5 py-0.5 rounded"
          style={{
            color: '#A8926A',
            background: 'rgba(6,6,15,0.7)',
            border: '1px solid rgba(168,146,106,0.3)',
          }}
        >
          {post.slot.day.toUpperCase()} · {post.slot.time}
        </span>
      </div>
    </div>
  );
}
