import type { Room } from '../types';
import { dateFormatted } from './brand';

const MY = dateFormatted.monthYear;

export const ROOMS: Room[] = [
  {
    id: 'growth',
    label: 'Growth Signals + Decisions',
    icon: '📡',
    short: 'Growth',
    color: '#4ADE80',
    description: 'Early market signals and decision context for where growth may emerge',
    cfoQuestion: 'Where should we move next?',
    micsServices: 'Strategic Advisory, Feasibility, M&A, Valuation, Expansion',
    serviceDetails: [
      'Strategic & Business Advisory',
      'Feasibility Studies & Market Entry Advisory',
      'Expansion & Restructuring Advisory',
      'Financial Modelling & Scenario Analysis',
      'Valuation & Investment Readiness',
      'Strategic Finance Support (board / management level)',
      'Strategic Finance & Capital Allocation',
      'M&A (Buy-side / Sell-side) & Exit Readiness',
      'Succession, Continuity & Shareholder Structuring',
    ],
    topics: [
      `UAE GDP forecast ${MY}`,
      `Dubai FDI Q2 ${dateFormatted.year}`,
      `GCC IPO ${dateFormatted.year}`,
      `DIFC registrations April ${dateFormatted.year}`,
      `UAE non-oil expansion ${dateFormatted.year}`,
      `Saudi Arabia mega project investments ${dateFormatted.year}`,
      `Abu Dhabi sovereign fund investments ${dateFormatted.year}`,
      `Dubai DMCC new registrations ${dateFormatted.year}`,
    ],
  },
  {
    id: 'capital',
    label: 'Capital, Cash & Treasury',
    icon: '🏦',
    short: 'Capital',
    color: '#F0C050',
    description: 'Cash visibility, capital deployment, and value preservation',
    cfoQuestion: 'How do we protect and deploy capital?',
    micsServices: 'Wealth Management, Cash Flow, Capital Structuring, SPVs',
    serviceDetails: [
      'Corporate Wealth Management (corporate & shareholder level)',
      'Cash Flow & Financial Health Reviews',
      'Capital Structuring, SPVs & Holding Structures',
      'Profit Repatriation & Distribution Structuring',
    ],
    topics: [
      `CBUAE rate decision April ${dateFormatted.year}`,
      `UAE bond market ${dateFormatted.year}`,
      `Dubai yields ${dateFormatted.year}`,
      `GCC private credit ${dateFormatted.year}`,
      `UAE dirham peg implications ${dateFormatted.year}`,
      `GCC sukuk market ${dateFormatted.year}`,
      `UAE corporate cash management trends ${dateFormatted.year}`,
    ],
  },
  {
    id: 'risk',
    label: 'Risk, Compliance & Governance',
    icon: '🛡️',
    short: 'Risk',
    color: '#EF5555',
    description: 'Regulatory developments, compliance, and governance themes',
    cfoQuestion: 'What could break us later?',
    micsServices: 'Corporate Tax, VAT, AML, Audit, OECD Pillar 2, Governance',
    serviceDetails: [
      'Corporate Tax & VAT advisory and compliance',
      'Business compliance & ongoing regulatory support',
      'Internal audit & risk advisory',
      'Anti Money Laundering (AML) / compliance risk assessments',
      'Corporate governance & control frameworks',
      'Business licensing, renewals & regulatory approvals',
      'Succession, continuity & shareholder structuring',
      'E-Invoicing',
      'DMTT / Pillar 2 / OECD',
    ],
    topics: [
      `UAE corporate tax April ${dateFormatted.year}`,
      `FTA compliance ${dateFormatted.year}`,
      `FATF UAE ${dateFormatted.year}`,
      `OECD DMTT UAE ${dateFormatted.year}`,
      `UAE e-invoicing mandate ${dateFormatted.year}`,
      `ESG disclosure requirements GCC ${dateFormatted.year}`,
      `UAE AML enforcement ${dateFormatted.year}`,
    ],
  },
  {
    id: 'world',
    label: 'World Pulse',
    icon: '🌍',
    short: 'World',
    color: '#5B8DEE',
    description: 'Global shifts not yet covered by UAE media',
    cfoQuestion: 'What global shifts will hit our region next?',
    micsServices: 'International Advisory, Cross-border Structuring',
    serviceDetails: [
      'International Advisory & Cross-border Structuring',
      'Global regulatory impact analysis for GCC entities',
      'Trade corridor advisory (GCC-Asia, GCC-Europe)',
    ],
    topics: [
      `global financial regulation April ${dateFormatted.year}`,
      `emerging markets shift ${dateFormatted.year}`,
      `US Fed policy impact GCC ${dateFormatted.year}`,
      `EU CBAM trade impact ${dateFormatted.year}`,
      `China Belt Road GCC impact ${dateFormatted.year}`,
      `BRICS expansion implications GCC ${dateFormatted.year}`,
      `global AI regulation financial sector ${dateFormatted.year}`,
    ],
  },
];
